// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/snake.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the type of messages
type MessageType int32

const (
	MessageType_UNKNOWN MessageType = 0
	MessageType_MOVE    MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "MOVE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN": 0,
		"MOVE":    1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_snake_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_snake_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_snake_proto_rawDescGZIP(), []int{0}
}

// Define move directions as binary values
type MoveDirection int32

const (
	MoveDirection_DOWN  MoveDirection = 0
	MoveDirection_RIGHT MoveDirection = 1
	MoveDirection_LEFT  MoveDirection = 2
	MoveDirection_UP    MoveDirection = 3
)

// Enum value maps for MoveDirection.
var (
	MoveDirection_name = map[int32]string{
		0: "DOWN",
		1: "RIGHT",
		2: "LEFT",
		3: "UP",
	}
	MoveDirection_value = map[string]int32{
		"DOWN":  0,
		"RIGHT": 1,
		"LEFT":  2,
		"UP":    3,
	}
)

func (x MoveDirection) Enum() *MoveDirection {
	p := new(MoveDirection)
	*p = x
	return p
}

func (x MoveDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_snake_proto_enumTypes[1].Descriptor()
}

func (MoveDirection) Type() protoreflect.EnumType {
	return &file_proto_snake_proto_enumTypes[1]
}

func (x MoveDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveDirection.Descriptor instead.
func (MoveDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_snake_proto_rawDescGZIP(), []int{1}
}

// Header message
type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type MessageType `protobuf:"varint,2,opt,name=type,proto3,enum=snakeup.MessageType" json:"type,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_snake_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Header) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

// Body message for move
type MoveBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset MoveDirection `protobuf:"varint,1,opt,name=offset,proto3,enum=snakeup.MoveDirection" json:"offset,omitempty"`
}

func (x *MoveBody) Reset() {
	*x = MoveBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveBody) ProtoMessage() {}

func (x *MoveBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveBody.ProtoReflect.Descriptor instead.
func (*MoveBody) Descriptor() ([]byte, []int) {
	return file_proto_snake_proto_rawDescGZIP(), []int{1}
}

func (x *MoveBody) GetOffset() MoveDirection {
	if x != nil {
		return x.Offset
	}
	return MoveDirection_DOWN
}

// Main message wrapper
type SnakeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are assignable to Body:
	//	*SnakeMessage_Move
	Body isSnakeMessage_Body `protobuf_oneof:"body"`
}

func (x *SnakeMessage) Reset() {
	*x = SnakeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snake_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnakeMessage) ProtoMessage() {}

func (x *SnakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snake_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnakeMessage.ProtoReflect.Descriptor instead.
func (*SnakeMessage) Descriptor() ([]byte, []int) {
	return file_proto_snake_proto_rawDescGZIP(), []int{2}
}

func (x *SnakeMessage) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (m *SnakeMessage) GetBody() isSnakeMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *SnakeMessage) GetMove() *MoveBody {
	if x, ok := x.GetBody().(*SnakeMessage_Move); ok {
		return x.Move
	}
	return nil
}

type isSnakeMessage_Body interface {
	isSnakeMessage_Body()
}

type SnakeMessage_Move struct {
	Move *MoveBody `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

func (*SnakeMessage_Move) isSnakeMessage_Body() {}

var File_proto_snake_proto protoreflect.FileDescriptor

var file_proto_snake_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x75, 0x70, 0x22, 0x42, 0x0a, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x75, 0x70, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x3a, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x2e, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73,
	0x6e, 0x61, 0x6b, 0x65, 0x75, 0x70, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x68, 0x0a, 0x0c,
	0x53, 0x6e, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73,
	0x6e, 0x61, 0x6b, 0x65, 0x75, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x75, 0x70, 0x2e, 0x4d, 0x6f,
	0x76, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x06,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x2a, 0x24, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x2a, 0x36, 0x0a, 0x0d,
	0x4d, 0x6f, 0x76, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x47, 0x48, 0x54,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02,
	0x55, 0x50, 0x10, 0x03, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x41, 0x64, 0x61, 0x6d, 0x41, 0x7a, 0x75, 0x64, 0x64, 0x69, 0x6e, 0x2f, 0x73,
	0x6e, 0x61, 0x6b, 0x65, 0x75, 0x70, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_snake_proto_rawDescOnce sync.Once
	file_proto_snake_proto_rawDescData = file_proto_snake_proto_rawDesc
)

func file_proto_snake_proto_rawDescGZIP() []byte {
	file_proto_snake_proto_rawDescOnce.Do(func() {
		file_proto_snake_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_snake_proto_rawDescData)
	})
	return file_proto_snake_proto_rawDescData
}

var file_proto_snake_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_snake_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_snake_proto_goTypes = []interface{}{
	(MessageType)(0),     // 0: snakeup.MessageType
	(MoveDirection)(0),   // 1: snakeup.MoveDirection
	(*Header)(nil),       // 2: snakeup.Header
	(*MoveBody)(nil),     // 3: snakeup.MoveBody
	(*SnakeMessage)(nil), // 4: snakeup.SnakeMessage
}
var file_proto_snake_proto_depIdxs = []int32{
	0, // 0: snakeup.Header.type:type_name -> snakeup.MessageType
	1, // 1: snakeup.MoveBody.offset:type_name -> snakeup.MoveDirection
	2, // 2: snakeup.SnakeMessage.header:type_name -> snakeup.Header
	3, // 3: snakeup.SnakeMessage.move:type_name -> snakeup.MoveBody
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_snake_proto_init() }
func file_proto_snake_proto_init() {
	if File_proto_snake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_snake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snake_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnakeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_snake_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SnakeMessage_Move)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_snake_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_snake_proto_goTypes,
		DependencyIndexes: file_proto_snake_proto_depIdxs,
		EnumInfos:         file_proto_snake_proto_enumTypes,
		MessageInfos:      file_proto_snake_proto_msgTypes,
	}.Build()
	File_proto_snake_proto = out.File
	file_proto_snake_proto_rawDesc = nil
	file_proto_snake_proto_goTypes = nil
	file_proto_snake_proto_depIdxs = nil
}
